version: '3'

services:
  php-web:
    image: php:7.4-apache
    container_name: php-web
    ports:
      - "8082:80"  # Change the host port if needed
    volumes:
      - ./php-web:/var/www/html  # Mounting the PHP application code into the container

  php-web-db:
    image: mysql:5.7
    container_name: php-web-db
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: php_web_db
      MYSQL_USER: php_web_user
      MYSQL_PASSWORD: php_web_password
    ports:
      - "3307:3306"  # Change the host port if needed
    volumes:
      - php-web-db-data:/var/lib/mysql  # Persisting MySQL data to a named volume

volumes:
  php-web-db-data:  # Named volume for MySQL data persistence
